name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies and run tests
      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      # Build Docker image
      - name: Build Docker image
        run: docker build -t testapp .

      # Push Docker image to Docker Hub (optional)
      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          docker tag testapp singhcsm/testapp:latest
          docker push singhcsm/testapp:latest

        #deploy to ec2 instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop testapp || true
            docker rm testapp || true
            docker rmi singhcsm/testapp:latest || true
            docker pull singhcsm/testapp:latest
            docker run -d -p 80:80 --name testapp singhcsm/testapp:latest
